name: Performance test

on:
  workflow_dispatch: # Allows manual triggering of the performance test workflow.

jobs:
  install-jmeter:
    uses: ./.github/workflows/01-jmeter-installation.yml # Call reusable workflow

  run-jmeter:
    uses: ./.github/workflows/02-jmeter-run.yml # Call reusable workflow

  publish-jmeter-report:
    uses: ./.github/workflows/03-jmeter-publish-report.yml # Call reusable workflow
