name: Publish JMeter Report

on:
  repository_dispatch:
    types: [publish-jmeter-report]

jobs:
  publish-jmeter-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download JMeter Report
        uses: actions/download-artifact@v3
        with:
          name: jmeter-report-${{ env.RUN_ID }}

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: report-${{ env.RUN_ID }}
