name: All integrated performance test 

on:
  workflow_dispatch: # Allows manual triggering of the performance test workflow.

permissions:
  contents: write  # Required to push changes to gh-pages
  pages: write     # Required to update GitHub Pages  

jobs:
    install-run-jmeter-publish-report:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Install JMeter
              run: |
                curl -o apache-jmeter-5.6.3.tgz https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
                tar -xvzf apache-jmeter-5.6.3.tgz          
                echo "JMeter installation complete."

        #run-jmeter:
            - name: Generate Unique Identifier
              id: generate-id
              run: echo "RUN_ID=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

            - name: Run JMeter Test Plan
              run: |
                ./apache-jmeter-5.6.3/bin/jmeter -n -t tests/performance-test.jmx -l test-results-${RUN_ID}.jtl -e -o report-${RUN_ID}
              env:
                RUN_ID: ${{ env.RUN_ID }}

            - name: Save JMeter Report
              uses: actions/upload-artifact@v4
              with:
                name: jmeter-report-${{ env.RUN_ID }}
                path: report-${{ env.RUN_ID }}
        
        #publish-jmeter-report:  
            - name: Is jmeter installed?
              run: |
                pwd
                ls              

            - name: Is jmeter installed?
              run: |
                pwd
                ls
                ls report*
            - name: Checkout gh-pages branch
              uses: actions/checkout@v3
              with:
                path: repo
                ref: gh-pages  # gh-pages branch

            - name: Is jmeter installed?
              run: |
                pwd
                ls
                ls repo
  
            - name: Copy JMeter Report to gh-pages directory
              run: |
                mkdir -p repo/reports/${RUN_ID}
                cp -r report-${RUN_ID}/* repo/reports/${RUN_ID}/

            - name: Commit and Push Reports to gh-pages
              run: |
                cd repo
                git config --local user.email "github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                git add reports/${RUN_ID}
                git commit -m "Add JMeter report for ${RUN_ID}"
                git push origin gh-pages

            - name: Publish to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: reports
                publish_branch: gh-pages
                keep_files: true  # Preserve existing files in gh-pages